### ISSUE TITLE
[Bug]: 12v battery voltage now missing

### ISSUE THREAD

**Issue by DragonSorcerer** [kvanbiesen/bmw-cardata-ha#95]
Since updating today the entry of the voltage from the 12v battery is now longer available for my 430i. It was showing 14.8v when the integration was first loaded and went to 15v during the last update about a week ago. Now gone ?

entity name was: sensor.430i_battery_voltage_12v

**Comment by kvanbiesen** [comment]
Next time properly fill in the template or at least attempt to givve some info

But i think i know what cause it, i fixed it in https://github.com/kvanbiesen/bmw-cardata-ha/commit/f1ba7daa1ad883c2ed5ccb9b1599f6750c150de7 . Thats integrated in 4.4.0. upgrade and it should be back

**Comment by DragonSorcerer** [comment]
sorry about the lack of info, this is my first interaction with GitHub and my only Custom integration (I'm also 60 !)

I've installed 4.4.0 and forced an update from the car and I still do not have the battery level back.
The attribute on the BMW Cardata site is this one I think...

vehicle.electricalSystem.battery.voltage | The value indicates the current battery voltage in the vehicle's electrical system. This value is always given in voltage, e.g. 14.4 V.

it was working in 4.2.8 and earlier

**Comment by kvanbiesen** [comment]
not all mqtt messages get instantly updated with a forced update. Sometimes you only get an update while actually driving or it has to change. Car batterij shouldnt be 14.4 in idle state, so let it sit for a while, and then drive it arround so it drops and when the alternator is charging it it should go back to 14.4, forcing an update

**Comment by DragonSorcerer** [comment]
Made several short trips over the weekend and a longer one today but still no battery voltage appearing. I do however now have tyre temperatures which were not there before.

**Comment by DragonSorcerer** [comment]
It's back ! Drove 300 miles today and it's now reappeared. Thanks for your help and keep up the great work on this.

**Comment by kvanbiesen** [comment]
Yay
